BEGIN;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS gender VARCHAR(255),
ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE,
ADD COLUMN IF NOT EXISTS phone VARCHAR(255),
ADD COLUMN IF NOT EXISTS blood_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS birth_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS reset_password_token VARCHAR(255),
ADD COLUMN IF NOT EXISTS verify_email_token VARCHAR(255),
ADD COLUMN IF NOT EXISTS is_verified INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_donation_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS donation_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS public_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS url_file VARCHAR(255),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

COMMIT;